kind: Service
apiVersion: v1
metadata:
  name: main-server-service
spec:
  selector:
    # Selector tells the service which pods to monitor, and which Pod to send the traffic to. Very important to exactly match the pod name ->
    app: main-server
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
